
#gre  ip_tunnel	ipip  nsh  ovbench.h  udp_tunnel  vxlan

all:
	make -C ip_tunnel
	make -C ipip 
	make -C nsh
	make -C udp_tunnel
	make -C vxlan

clean:
	make -C ip_tunnel clean
	make -C ipip clean
	make -C nsh clean
	make -C udp_tunnel clean
	make -C vxlan clean
